version: '3.8'

services:
  url-shortener-1:
    build: .
    volumes:
      - .:/url_shortener
    ports:
      - "9292:9292"
    depends_on:
      - mongo
      - etcd-1
      - etcd-2
      - etcd-3
    environment:
      MONGO_URL: "mongodb://mongo:27017/url_shortener"
      ETCD_URL: "http://etcd-1:2379, http://etcd-2:2379, http://etcd-3:2379"
      SERVICE_NAME: url-shortener-1

  url-shortener-2:
    build: .
    volumes:
      - .:/url_shortener
    ports:
      - "9293:9292"
    depends_on:
      - mongo
      - etcd-1
      - etcd-2
      - etcd-3
    environment:
      MONGO_URL: "mongodb://mongo:27017/url_shortener"
      ETCD_URL: "http://etcd-1:2379, http://etcd-2:2379, http://etcd-3:2379"
      SERVICE_NAME: url-shortener-2

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  etcd-1:
    image: quay.io/coreos/etcd:v3.4.13
    entrypoint: /usr/local/bin/etcd
    ports:
      - "2379:2379"
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'

  etcd-2:
    image: quay.io/coreos/etcd:v3.4.13
    entrypoint: /usr/local/bin/etcd
    ports:
      - "2378:2379"
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://etcd-2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-2:2379'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'

  etcd-3:
    image: quay.io/coreos/etcd:v3.4.13
    entrypoint: /usr/local/bin/etcd
    ports:
      - "2376:2379"
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://etcd-3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-3:2379'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'

volumes:
  mongo-data: